### PR TITLE
Naming Schemes/Name Conventions

### PR DESCRIPTION
**Pull request by Leo40Git**
This PR adds the following features:
- A `SerializedName` annotation, which allows changing the name of a `TrackedValue` derived from a field.
- The [`NamingScheme`](https://github.com/SpongePowered/Configurate/blob/master/core/src/main/java/org/spongepowered/configurate/util/NamingScheme.java) interface and the [`NamingSchemes`](https://github.com/SpongePowered/Configurate/blob/master/core/src/main/java/org/spongepowered/configurate/util/NamingSchemes.java) enum, straight from Configurate.
- The `NameConvention` annotation, which allows specifying the `NamingScheme` to use for getting `TrackedValue` names from field names (via `NamingSchemes`, or using a custom `NamingScheme` implementation).
- A `.gitignore` file, copied from [Quilt Standard Libraries](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/.gitignore).

Notes:
- Both `NameConvention.custom()` and `NameConvention.value()` can be set at the same time, but `NameConvention.custom()` takes priority.
- Sections inherit the main config class's `NameConvention` by default. 
- Sections can have different `NameConvention`s for their nested values. A `NameConvention` annotation can be added both to the section class and to the section field, with the annotation on the field taking priority.
- The default naming scheme is `PASSTHROUGH`, for backwards compatibility.

### CODE REVIEW

**Comment by Leo40Git** [comment]
Bump!

**Comment by Leo40Git** [comment]
B U M P

**Comment by TheGlitch76** [comment]
New maintainer here--I'll get to this PR eventually, but it's going to sit on the backburner for a while.

I'm currently concerned with a [2.0 branch](https://github.com/QuiltMC/quilt-config/tree/next) where i'm experimenting with changes (breaking or not) which improve the current API structure and make it... well... actually usable. When all of that is resolved and somehow integrated into Quilt Loader, then we can move on to extensions like this.

**Comment by Leo40Git** [comment]
I should probably update this now that #8 is merged, huh?

**Comment by Leo40Git** [comment]
Closed due to containing code from a particularly cringe individual.

**Comment by Leo40Git** [comment]
Closing for now, may reopen this later.

**Pull request closed without merging**
